### ISSUE TITLE
Another workaround for the interface -> implementation problem

### ISSUE THREAD

**Issue by gustavohenke** [asvetliakov/Huject#4]
Hey there!
First of all, thank you very much for this amazing library.
I'm studying DI for Java really hard, and because of this library, I decided to migrate a plain Node.js project to TS to make use of DI :heart: 

So, going to the point of this issue:
I think I found another workaround for the problem mentioned in the readme regarding interfaces referentiation in TS.

Take a look:

``` ts
/// <reference path="../node_modules/huject/huject.d.ts" />
"use strict";

import { Container, Inject } from "huject";

interface TestInterface {
    method1(): void;
}

class TestImpl implements TestInterface {
    public method1(): void {
        console.log("foo");
    }
}

class Controller {
    @Inject("test")
    public test: TestInterface;
}


const container = new Container();
container.register("test", TestImpl);
container.register(Controller);

const ctrl: Controller = container.resolve(Controller);
ctrl.test.method1();
```

What do you think?
I have NO experience with TS.

Oh, and if you don't reply in time, I wish you a happy new year! :tada: :tada:

**Comment by asvetliakov** [comment]
This method will work too, but it's not best way because:
1) You need to specify both interface type and interface string literal (to specify injection). So you're doing same thing two times.
2) You will lose IDE benefits such as autocompleting, usage and auto-refactoring when using string literal
3) You will not be able to easy mock such interface in any mocking library (same applies to abstract methods in abstract classes too)
Currently, from my point, TS interfaces are usable only for anonymous object declarations such as configuration objects in libraries, JSON.parse-ed objects from backend and similar.
May be TS developers will fix that sometime (if devs will ignore ts interfaces mostly and use such libraries, as my), but now they don't want to do it.

And Happy New Year anyone. Feliz Año Nuevo.

**Comment by gustavohenke** [comment]
OK, you win!
I was going to suggest enums instead of strings, but that would make no difference at all.

What a shame that TS developers don't export interface metadata :(

**Comment by asvetliakov** [comment]
Yeah, there is a space for improvements, hope they'll do it sometime.
Closing issue, if you'll have any ideas for improvements - welcome :)
